import type { ProfileSnapshot } from "@/lib/profile/editor";
import { estimateYearsOfExperience } from "@/lib/job-monitoring/triage/state";
import type { SearchPreferences } from "@/lib/search-preferences";

import type { FieldMapping } from "./field-mapping";
import type { FormField, KitAnswer, KitAnswers } from "./types";

/** Picks the option that best matches an answer ("No" -> "No, I do not..."), or keeps the text. */
export function pickOption(answer: string, options: string[] | undefined): string {
  if (!options || options.length === 0) {
    return answer;
  }

  const wanted = answer.trim().toLowerCase();
  const exact = options.find((option) => option.trim().toLowerCase() === wanted);

  if (exact) {
    return exact;
  }

  const starts = options.find((option) => option.trim().toLowerCase().startsWith(wanted));

  if (starts) {
    return starts;
  }

  const yesNo = /^(yes|no)\b/.exec(wanted)?.[1];

  if (yesNo) {
    const match = options.find((option) => option.trim().toLowerCase().startsWith(yesNo));

    if (match) {
      return match;
    }
  }

  const contains = options.find((option) => option.toLowerCase().includes(wanted) || wanted.includes(option.trim().toLowerCase()));

  return contains ?? answer;
}

export type BuildAnswersInput = {
  fields: FormField[];
  mappings: Record<string, FieldMapping>;
  profile: ProfileSnapshot;
  preferences: SearchPreferences | null;
  coverLetter: string | null;
  hasResume: boolean;
  /** Drafts for `free_text` fields (id -> text), already generated. */
  freeTextDrafts?: Record<string, string>;
  now?: Date;
};

const PREFERENCE_KEYS = [
  "us_work_authorization",
  "requires_sponsorship",
  "salary_expectation",
  "notice_period",
  "how_did_you_hear",
] as const;

/**
 * Turns the mapping into answers from the profile and the saved default answers.
 * Anything missing stays `null` for the user; EEO/demographic fields are never
 * answered; drafts generated by a model are flagged `aiDraft`.
 */
export function buildKitAnswers(input: BuildAnswersInput): KitAnswers {
  const { profile, preferences } = input;
  const answers: KitAnswers = {};
  const [firstName, ...rest] = profile.fullName.trim().split(/\s+/);
  const years = Math.floor(estimateYearsOfExperience(profile.experiences, input.now));

  for (const field of input.fields) {
    const mapping = input.mappings[field.id];
    const key = mapping?.key ?? "unknown";
    const base = { key, confidence: mapping?.confidence } as const;
    let answer: KitAnswer;

    switch (key) {
      case "eeo_demographic":
        answer = { ...base, value: null, source: "none", note: "Pergunta demográfica: responda você mesmo." };
        break;
      case "full_name":
        answer = { ...base, value: profile.fullName, source: "profile" };
        break;
      case "first_name":
        answer = { ...base, value: firstName ?? null, source: "profile" };
        break;
      case "last_name":
        answer = { ...base, value: rest.join(" ") || null, source: "profile" };
        break;
      case "email":
        answer = { ...base, value: profile.email, source: "profile" };
        break;
      case "phone":
        answer = { ...base, value: profile.phone, source: "profile" };
        break;
      case "linkedin":
        answer = { ...base, value: profile.linkedin, source: "profile" };
        break;
      case "github":
        answer = { ...base, value: profile.github, source: "profile" };
        break;
      case "portfolio":
        answer = { ...base, value: profile.projects.find((project) => project.url)?.url ?? profile.github, source: "profile" };
        break;
      case "location":
        answer = { ...base, value: profile.location, source: "profile" };
        break;
      case "years_experience":
        answer = { ...base, value: years > 0 ? String(years) : null, source: "profile" };
        break;
      case "timezone":
        answer = { ...base, value: preferences?.timezone ?? null, source: "preferences" };
        break;
      case "resume_upload":
        answer = { ...base, value: input.hasResume ? "resume.pdf" : null, source: "resume", note: input.hasResume ? "Anexe o PDF do kit." : "Currículo em inglês não foi gerado." };
        break;
      case "cover_letter":
        answer = { ...base, value: input.coverLetter, source: "cover_letter" };
        break;
      case "free_text": {
        const draft = input.freeTextDrafts?.[field.id];

        answer = draft
          ? { ...base, value: draft, source: "ai_draft", aiDraft: true, note: "Rascunho IA: revise antes de enviar." }
          : { ...base, value: null, source: "none" };
        break;
      }
      default:
        if ((PREFERENCE_KEYS as readonly string[]).includes(key)) {
          const stored = preferences?.defaultAnswers[key as (typeof PREFERENCE_KEYS)[number]];

          answer = stored
            ? { ...base, value: stored, source: "preferences" }
            : { ...base, value: null, source: "none", note: "Sem resposta padrão: cadastre em Perfil, Busca internacional." };
        } else {
          answer = { ...base, value: null, source: "none" };
        }
    }

    if (answer.value && (field.type === "select" || field.type === "radio")) {
      answer = { ...answer, value: pickOption(answer.value, field.options) };
    }

    answers[field.id] = answer;
  }

  return answers;
}

/** Fields whose answer is still empty and that the user must fill by hand. */
export function unansweredFields(fields: FormField[], answers: KitAnswers): FormField[] {
  return fields.filter((field) => !answers[field.id]?.value);
}
